Feature/navigation mobile
MateuszMalec1611/photography pull request #4
Opened 2020-10-13 11:58 UTC by MateuszMalec1611

2020-10-13 16:22 UTC, mmajk55 requested changes
Sprawdź komentarze i daj znać jak poprawisz

2020-10-13 16:22 UTC, mmajk55 commented on index.html
> +    <div style="height: 200vh;"></div>
Staraj się nie używać inline styli, tylko dodaj klasę i ją ostyluj.
Dlaczego tutaj 200vh?

2020-10-13 16:22 UTC, mmajk55 commented on scss/_about-us.scss
> +#about-us {
Staraj się stylować po klasach nie po id. 

- Oficjalna dokumentacja na temat hierarchi selektorów: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity 
PL: https://blog.strefakursow.pl/specyfikacja-selektorow-css/

2020-10-13 16:22 UTC, mmajk55 commented on scss/_extra-classes.scss
> +.nav-links::after {
Pseudoklasę ::after dodaj w selektorze `.nav-links` w pliku ze stylami nawigacji. Powinno to wyglądać tak
```
.nav-links {
   ...jakieś style
   &::after {
      ... style dla aftera
   }
}
```
W pliku _extra-classes.scss dodawaj tylko style dla klas używanych globalnie

2020-10-13 16:22 UTC, mmajk55 commented on scss/_navigation.scss
> +    .nav-links:hover::after {
pseudoklasy dodawaj pod jednym selektorem. znak `&` odnosi się do selektora w którym jest użyty, czyli powinieneś zrobić to tak:
```
.nav-links {
  ...jakieś style
   &::hover::after {
      ...style
   }
}

2020-10-15 17:50 UTC, MateuszMalec1611 commented on index.html
> +    <div style="height: 200vh;"></div>
to dodałem po to aby móc sobie zjechać niżej...

2020-10-16 18:34 UTC, merged